fix: update method
edigar/noobframework pull request #8
Opened 2021-09-22 03:24 UTC by Gessilt

The updateValues was added to the update method, because the condition value was not being changed in dispatch, it is now, for verification, line 150. That's all, folks

2021-09-25 15:46 UTC, edigar requested changes
Excelente descoberta! Porém ainda existe um problema aí.
Adicionei uma sugestão de correção.
Valeu! 👍

2021-09-25 15:46 UTC, edigar commented on core/DataBase.php
>              $conditions[":$column"] = $value;
```suggestion
```
Perceba que a linha 149 é igual a linha 150, com exceção do nome da variável (na hora de criar/corrigir, devo ter confundido os nomes das variáveis). Esse é o erro. Essa linha 149 ainda vai adicionar um erro ao SQL. Se puder corrigir esse PR apagando-a, ficará TOP.
Obrigado pela contribuição!

2021-09-25 15:53 UTC, Gessilt commented
Ok, sugestão aceita e commit feito. Agora basta aceitar e fazer o merge, obrigado Edigar.

2021-09-28 19:09 UTC, edigar approved these changes
💯

2021-10-01 21:47 UTC, merged